### PR TITLE
Updated data for MX; New Scenarios

### PR DESCRIPTION
**Pull request by travisfranck**
CPL has updated data in Buildings, Transport, and some of the default policies for BAU, like RPS and Carbon Tax.  This was done in conjunction with ICM. In addition, there are new scenarios and FoPITY for implementing those policies.

Another important change is that the model has been saved using Vensim's git-friendly features.  That means the MDL has been saved the newer file format, there are now MDLS files (user settings files) that aren't checked in, and the model has been saved in Terse mode.  Please open the model using Vensim 10.2.1 or newer, since there is a bug in v10.1 that corrupted the model when saved using Terse mode.

Additionally, we used Vensim submodel feature to add some "CPL_Additions" to the EPS.  This allows us to make some additional calculations without changing the main EPS.mdl file (other than the Git settings above, and linking to the CPL_Additions.mdl file).

The beta web app will need to be updated after this PR has been merged.

### CODE REVIEW

**Comment by travisfranck** [comment]
@ToddFincannonEI I can merge this (big green button!) because I have access, but I thought you or Olivia should take a look it the first time, so see if you'd like changes.  Your comments could be about git-style and/or model or data issues.  Thanks.

**Comment by ToddFincannonEI** [comment]
Olivia has not been involved with this model recently, so I added Rachel as a reviewer instead. I believe the team has all standardized on Vensim 9.2.4 to better support our large sketches in EPS. I've been using 10.2.1 myself to get working CMD scripts that I need to automate validation. @travisfranck could you say more about the Git-friendly features you're using? The last time that Jeff tried them, they didn't work for us. Pointers to docs would be enough for now. We also have not used Vensim modules before. We'll have to see how that works with SDEverywhere.

**Comment by travisfranck** [comment]
( mentioning @Saidou92 so he can follow this thread. )

I think that standardizing on a version of Vensim does make sense.  We've felt that the latest has been working pretty well, especially better on macOS.  FWIW, we've been using EPS with 10.x without major problems. In general I we've been running the latest versions because the have helpful bug fixes.

Git-friendly isn't hard.  There is a button (should be in v9) that help you choose the values. The key things that happen are:

1. it applies a linter/formatter to the MDL so that there is consistency in equation writing
2. Previously some personal settings (like which tool a user had selected in the toolbar) was saved into the MDL file.  Now these are saved into separate "mdls" files that hold user-specific settings. (not saved to repo)

There was a bug in "Terse Equations" that corrupted the EPS model in 10.1 but I reported it and it was fixed in 10.2.  I think it might be present in 9.2, which is maybe why it didn't work when Jeff tried it.

Vensim modules are great.  They work fine with SDE since CI's been using them since... 2021?

Here is a screenshot of the Settings. The button in the upper right corner auto-sets all the other fields.  I might have changed the style to Terse and I also changed the Override Sketch Zoom to 100% (instead of Fit to Screen).

Screenshot 2024-10-10 at 10 21 40 AM

**Comment by travisfranck** [comment]
@rgolds1203 @ToddFincannonEI Hope we can merge and publish a new webapp this week because we'd like the useful wedge graphs for a report.  Thank you.

**Comment by ToddFincannonEI** [comment]
Thanks for the Vensim details, @travisfranck  — I passed them on to Robbie, who will see how they work for us. I was able to build the app after making one small change to the model. However, it fails at runtime because of a config error. The build process is designed for the "classic" model save format. It is not picking up subscript definitions in the Git-friendly format. We definitely want to support this, so I will work on getting the build system working with the new format.

**Comment by travisfranck** [comment]
@ToddFincannonEI If it helps in the short-term, I could try saving the model in "Verbose" (instead of "terse") which might help write out the subscripts differently.  Let me know if you want me to do anything on this side.

**Comment by ToddFincannonEI** [comment]
Thanks, @travisfranck  — what I meant by the "classic" file format is the "verbose" or "originally entered" formats that we have used until now at EI. The EPS app build process does its own parse of the mdl file for subscript ranges. I was able to support the way that the terse format writes subscript ranges. That was the only fix I needed to build and validate the app. I will send a link by email shortly, and will come back here to note the changes I will push to the PR later today.

**Comment by ToddFincannonEI** [comment]
I pushed two commits to the develop_for_CPL branch. If these look OK, we can proceed with merging into develop, or could continue working on develop_for_CPL. We can build the app from either branch.

The first commit was some changes to the `EPS.mdl` file that rewrote the FoPITY lookup as an aux var, because SDEverywhere does not support the lookup syntax. I also took the liberty of merging changes to `.gitignore` that we use at EI.

The second commit rewrites the FoPITY input data files for better app compatibility. The Python script we used to generate FoPITY files before was writing any number of decimal places, whereas the app only uses 3 significant digits of precision. I replaced the Python script with a new `FoPITY.xlsx` file that has the same values but it is easier to work with. This xlsx file is the basis for generating FoPITY CSV files with the desired precision. It also does rounding in JavaScript, which is subtly different than rounding in Python, for compatibility with the app, which uses JavaScript.

If you change policy schedules in the future, edit the `FoPITY.xlsx` file, commit the changes, and let me know. I will generate new CSV files. This procedure will become self-service in the near future after I add it to the EPS app.

While validating the model after changing the FoPITY files, Vensim 10.2.2 was issuing a floating point error in 2050 for the BAU scenario. I didn't see any obvious cause for that, so to solve it I removed some entries for policy schedules 3 through 6 that are not used in the current reference scenario. I am pretty sure they are spurious, but we can restore them if necessary.

**Pull request merged**
